version: "3.7"
services:
  mongo:
    image: mongo:4.4.0
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ${PWD}/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo!234
